### PR TITLE
Revert "Allows to support newer versions of used symfony components."

### PR DESCRIPTION
**Pull request by goetas**
Reverts goetas/xsd2php#103

### CODE REVIEW

**Comment by sgasser** [comment]
Do you will support symfony 3.0 in the near future?

**Comment by goetas** [comment]
> Do you will support symfony 3.0 in the near future?

i will say yes. unfortunately in the last months i had really little time to work on this project. help is welcome :)

**Comment by sgasser** [comment]
Could you explain whats missing for symfony 3.0?

**Comment by goetas** [comment]
In SF3 the progress bar helper is changed. the current impl is https://github.com/goetas/xsd2php/blob/master/lib/Command/ConvertToPHP.php#L35 
some info about the new implementation are here https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md#console

**Pull request merged**
