### PR TITLE
Update AbstractConvert.php

### PR DESCRIPTION
**Pull request by z2z**
Enable recovery mode DOMdocument class.

### CODE REVIEW

**Comment by goetas** [comment]
XSDs by definition must be well formed... can you explain your user case?

**Comment by z2z** [comment]
I was not able to dom load url.

Composer script
`    "build": "php bin/xsd2php convert:php http://opentravel.org/2014B/FastRezBinding.xsd --ns-map=http://www.opentravel.org/OTA/2003/05;Mercurio/OTA/2007B/ --ns-dest=Mercurio/OTA/2007B/;00src/Mercurio/OTA/V2007B",
`

**Comment by goetas** [comment]
Sure? can you post the error message? http://opentravel.org/2014B/FastRezBinding.xsd looks good to me

**Comment by z2z** [comment]
PHP Warning:  DOMDocument::load(): I/O warning : failed to load external entity ....

**Comment by goetas** [comment]
Closing because of 

>XSDs by definition must be well formed...

**Pull request closed without merging**
